baseURL = "https://wvverez.github.io/blog/"
languageCode = "es-es"
title = "wvverez"
theme = "PaperMod"

[params]
env = "production"
defaultTheme = "dark"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true

[params.profileMode]
enabled = true
title = "wvverez"
subtitle = "Cybersecurity · Programming · Malware"
imageUrl = "/blog/images/avatar.png"
imageWidth = 150
imageHeight = 150
