baseURL = "https://wvverez.github.io/blog/"
languageCode = "es-es"
title = "Vulnerabilidad del mes"
theme = "PaperMod"

[params]
env = "production"
defaultTheme = "dark"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true

[params.profileMode]
enabled = true
title = "Vulnerabilidad del mes"
subtitle = "Cybersecurity · Programming · Active Directory"
imageUrl = "https://raw.githubusercontent.com/wvverez/blog/main/themes/PaperMod/images/avatar.png"
imageTitle = "wvverez"
imageWidth = 150
imageHeight = 150

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"
